unique_ids:
  assets:
    standard-page.html: 522WFHWKRQI67RJGOWJN7P6VKG2WGG6X
    theme.css: 6JS4X4AGANVHM7JVB2MLGRHXR6UUE5GD
  forms:
    Form1: FSFWDZSPBA2TAXJJ5YDP2GGFXS76LOS3
  modules: {}
  scripts: {}
  server_modules: {}
